(TeX-add-style-hook "redMex02"
 (lambda ()
    (LaTeX-add-bibliographies
     "../bib/magar")
    (LaTeX-add-labels
     "T:counterprops"
     "F:propsAndCost"
     "F:underOverRep"
     "F:malapp"
     "T:simIndex"
     "T:volatMarginsd0"
     "F:seatsVotes"
     "E:cubeLaw"
     "F:lambdaRhoEx"
     "F:posterior_s0s1s3"
     "F:malmgnat")
    (TeX-add-symbols
     "mc")
    (TeX-run-style-hooks
     "amsmath"
     "arydshln"
     "natbib"
     "sort"
     "longnamesfirst"
     "graphicx"
     "pdftex"
     "url"
     "hyperref"
     "setspace"
     ""
     "geometry"
     "bottom=1in"
     "top=1in"
     "left=1.25in"
     "right=1.25in"
     "letterpaper"
     "latex2e"
     "art12"
     "article"
     "12pt"
     "letter")))

