---
title: "2013 Party Action Analysis"
output: html_notebook
---
Read cleaned 2013 spreadsheet
```{r}
library(dplyr)
library(tidyr)


INE2013s1.df <- read.delim(file="Pre-Normalized APSA2014PaperTables - Obs 1st Scenario.tsv",stringsAsFactors =FALSE,na.strings="-")
INE2013s2.df <- read.delim(file="Pre-Normalized APSA2014PaperTables - Obs 2nd Scsnario .tsv",stringsAsFactors =FALSE,na.strings="-")
INE2017s1.df <- read.delim(file="Pre-Normalized Comparative Tables 2017 Federal (APSA 2019) - 1erEsc 2017.tsv",stringsAsFactors =FALSE,na.strings="-")
INE2017s2.df <- read.delim(file="Pre-Normalized Comparative Tables 2017 Federal (APSA 2019) - 2doEsc+final 2017.tsv",stringsAsFactors =FALSE,na.strings="-")



```

use scather/gather to normalize data

```{r}
normalizeEvent<-function(input.df) {
  # gather into key value pairs
  tmpgather.df<-gather(input.df,key="key",value="value",-Entidad)
  tmpgather.df["govlevel"]=sapply(strsplit(tmpgather.df[["key"]],'.',fixed=TRUE),function(x)x[[1]])
  tmpgather.df["actor"]=sapply(strsplit(tmpgather.df[["key"]],'.',fixed=TRUE),function(x)x[[2]])
  tmpgather.df["vtype"]<-sapply(strsplit(tmpgather.df[["key"]],'.',fixed=TRUE),function(x)if(length(x)==3){x[[3]]}else{"SCORE"})
  tmpgather.df<-subset(tmpgather.df,select=-key)
  # reassemble 
  tmpspread.df<-spread(tmpgather.df,key="vtype",value="value")
  # standardize dummy variables
  tmpspread.df["PROPOSED"]<-!is.na(tmpspread.df["SCORE"])
  if (!any(names(tmpspread.df)=="INVALID")) {
        tmpspread.df["INVALID"]<-NA
  }
  tmpspread.df[["INVALID"]]<-as.logical(tmpspread.df[["INVALID"]])
  if (!any(names(tmpspread.df)=="PAPER")) {
     tmpspread.df["PAPER"]<-NA
  }
  tmpspread.df[["PAPER"]]<-as.logical(tmpspread.df[["PAPER"]])
  return(tmpspread.df) 
}
```

2013 scenario 1
```{r}
# standardize names
names(INE2013s1.df)[which(names(INE2013s1.df)=="Primer.Escenario")]<-"CNV.Algorithm"
names(INE2013s1.df)[which(names(INE2013s1.df)=="RECOMENDACION.CT")]<-"CNV.Recomendacion"
# Recommendation is measured at different leval, and type complicates comparison
tmp2013s1.df<- normalizeEvent(subset(INE2013s1.df,select=-CNV.Recomendacion))
#tmp2013s1.df["scenario"]<-1
tmp2013s1.df["year"]<-2013
tmp2013s1.df["stage"]<-2
tmp2013s1.df[which(tmp2013s1.df["actor"]=="Algorithm"),"stage"] <- 1
```

Sample analysis 
```{r}
results<-xtabs(formula=PROPOSED~actor+govlevel,data=tmp2013s1.df)
print(results)
heatmap(results, scale="column", col=gray.colors(max(results)))
```
```{r}
#2013 Scenario 2
# normalize names
names(INE2013s2.df)[which(names(INE2013s2.df)=="Primer.Escenario")]<-"CNV.Algorithm"
names(INE2013s2.df)[which(names(INE2013s2.df)=="Segundo.Escenario")]<-"CNV.Segundo"
names(INE2013s2.df)[which(names(INE2013s2.df)=="Tercer.Escenario")]<-"CNV.Tercer"
names(INE2013s2.df)[which(names(INE2013s2.df)=="Junta.Local.Ejecutiva")]<-"CNV.Junta"
names(INE2013s2.df)[which(names(INE2013s2.df)=="Ganador")]<-"CNV.Ganador"
tmp2013s2.df <- normalizeEvent(subset(INE2013s2.df,select=-c(CNV.Ganador,CNV.Algorithm)))
tmp2013s2.df["year"]<-2013
#tmp2013s2.df["scenario"]<-2
tmp2013s2.df["stage"]<- 4
tmp2013s2.df[which(tmp2013s2.df["actor"]=="Segundo"),"stage"] <- 3
tmp2013s2.df[which(tmp2013s2.df["actor"]=="Segundo"),"actor"] <- "INE"
tmp2013s2.df[which(tmp2013s2.df["actor"]=="Tercer"),"stage"] <- 5
tmp2013s2.df[which(tmp2013s2.df["actor"]=="Tercer"),"actor"] <- "INE"


```
Analyze second
```{r}
results<-xtabs(formula=PROPOSED~actor+govlevel,data=tmp2013s2.df)
print(results)
heatmap(results, scale="column", col=gray.colors(max(results)))
```

2017 scenario 1
```{r}
# standardize names
names(INE2017s1.df)[which(names(INE2017s1.df)=="Primer.Escenario")]<-"CNV.Algorithm"
# Recommendation is measured at different leval, and type complicates comparison
tmp2017s1.df<- normalizeEvent(INE2017s1.df)
#tmp2017s1.df["scenario"]<-1
tmp2017s1.df["year"]<-2017
tmp2017s1.df["stage"]<-2
tmp2017s1.df[which(tmp2017s1.df["actor"]=="Algorithm"),"stage"] <- 1
```

Sample analysis 
```{r}
results<-xtabs(formula=PROPOSED~actor+govlevel,data=tmp2017s1.df)
print(results)
heatmap(results, scale="column", col=gray.colors(max(results)))
```

```{r}
#2017 Scenario  2
# normalize names
names(INE2017s2.df)[which(names(INE2017s2.df)=="Primer.Escenario")]<-"CNV.Algorithm"
names(INE2017s2.df)[which(names(INE2017s2.df)=="Segundo.Escenario")]<-"CNV.Segundo"
names(INE2017s2.df)[which(names(INE2017s2.df)=="Tercer.Escenario")]<-"CNV.Tercer"
tmp2017s2.df <- normalizeEvent(INE2017s2.df)
tmp2017s2.df["year"]<-2017
#tmp2017s2.df["scenario"]<-2
tmp2017s2.df["stage"]<- 4
tmp2017s2.df[which(tmp2017s2.df["actor"]=="Segundo"),"stage"] <- 3
tmp2017s2.df[which(tmp2017s2.df["actor"]=="Segundo"),"actor"] <- "INE"
tmp2017s2.df[which(tmp2017s2.df["actor"]=="Tercer"),"stage"] <- 5
tmp2017s2.df[which(tmp2017s2.df["actor"]=="Tercer"),"actor"] <- "INE"

```
Analyze second
```{r}
results<-xtabs(formula=PROPOSED~actor+govlevel,data=tmp2017s2.df)
print(results)
heatmap(results, scale="column", col=gray.colors(max(results)))
```


```
Merge and analyze
```
```{r}
proposals.df<-rbind(tmp2013s1.df ,tmp2013s2.df, tmp2017s1.df, tmp2017s2.df)

```

```{r}
results<-xtabs(formula=PROPOSED~actor+govlevel+stage,data=proposals.df)
```


```{r}
#Winning scores

winscores <- subset(proposals.df,stage==5, select=c(SCORE,year,Entidad))
names(winscores)[1]<-"Winning.Score"
print (winscores)
```

```{r}
twin<-proposals.df %>% inner_join(winscores)

#cat("Which actors won ...")
# by(twin,c(twin["Entidad"], twin["year"]),function(x)x["actor"],simplify=FALSE)

```


```{r}
# Analyze transparency compliance

cat ("Invalidations")
xtabs(PROPOSED~INVALID+year, proposals.df)
ftable(xtabs(PROPOSED~INVALID+actor+year+stage, proposals.df))

lowvalid <- aggregate(formula=SCORE~year+Entidad,data=subset(proposals.df,PROPOSED==TRUE & (is.na(INVALID) | INVALID==FALSE)),FUN=min)
names(lowvalid)[3]<-"Lowestv.Score"

unanimous <- aggregate(formula=SCORE~year+Entidad,data=subset(proposals.df,stage==4& PROPOSED==TRUE & (is.na(INVALID) | INVALID==FALSE)),FUN=function(x)length(unique(x))==1)
names(unanimous)[3]<-"UnanimousLast"



tmpBest<- within(merge(lowvalid,winscores, by= c("year","Entidad")), LowestWon<-(Lowestv.Score==Winning.Score))
tmpBest<-as_tibble(tmpBest)
xtabs(~LowestWon+year,tmpBest)

tmpBest<-merge(tmpBest,unanimous)
tmpBest<-within(tmpBest,RulesViolation <- !LowestWon & !UnanimousLast) 
round1p <- aggregate(formula=SCORE~year+Entidad,data=subset(proposals.df,stage==1),FUN=c)
 names(round1p)[3]<-"round1.scores"

 round2p <- aggregate(formula=SCORE~year+Entidad,data=subset(proposals.df,stage==2& PROPOSED==TRUE & (is.na(INVALID) | INVALID==FALSE)),FUN=c)
 names(round2p)[3]<-"round2.scores"
 round3p <- aggregate(formula=SCORE~year+Entidad,data=subset(proposals.df,stage==3& PROPOSED==TRUE & (is.na(INVALID) | INVALID==FALSE)),FUN=c)
  names(round3p)[3]<-"round3.scores"

 round4p <- aggregate(formula=SCORE~year+Entidad,data=subset(proposals.df,stage==4& PROPOSED==TRUE & (is.na(INVALID) | INVALID==FALSE)),FUN=c)
   names(round4p)[3]<-"round4.scores"

round5p <- aggregate(formula=SCORE~year+Entidad,data=subset(proposals.df,stage==5& PROPOSED==TRUE & (is.na(INVALID) | INVALID==FALSE)),FUN=c)
  names(round5p)[3]<-"round5.scores"
    tmpBest<-merge(tmpBest,round1p,all.x=TRUE)  

  tmpBest<-merge(tmpBest,round2p,all.x=TRUE)  
  tmpBest<-merge(tmpBest,round3p,all.x=TRUE)
    tmpBest<-merge(tmpBest,round4p,all.x=TRUE)
      tmpBest<-merge(tmpBest,round5p,all.x=TRUE)

tmpBest$IneNewRound3<-apply(tmpBest,1,function(x)length(intersect(unlist(x$round3.scores),union(unlist(x["round1.scores"]),unlist(x["round2.scores"]))))==0)

tmpBest$IneNewRound5<-apply(tmpBest,1,function(x)length(intersect(unlist(x$round5.scores),union(unlist(x["round3.scores"]),unlist(x["round4.scores"]))))==0)

tmpBest %<>% mutate(IneNew=IneNewRound3 | IneNewRound5)



cat("lowest valid proposal winning")
xtabs(~LowestWon+year,tmpBest)
cat("party unanimity in the last round")
xtabs(~UnanimousLast+year,tmpBest)
cat("Rules violation (not lowest & not unanimous)")
xtabs(~RulesViolation+year,tmpBest)

```


