(TeX-add-style-hook "uhBias2014"
 (lambda ()
    (TeX-run-style-hooks
     "multirow"
     "tabulary"
     "tikz"
     "color"
     "graphicx"
     "amsmath"
     "babel"
     "es-nodecimaldot"
     "spanish"
     "inputenc"
     "ansinew"
     "fontenc"
     "T1"
     "ae"
     "url"
     "beamerthemesplit"
     "pifont"
     ""
     "latex2e"
     "beamer10"
     "beamer"
     "xcolor=dvipsnames")))

