#+SEQ_TODO: CONCEDED ELABORATED DEFENDED | NO_ACTION_NEEDED DONE DROPPED
#+LaTeX_CLASS_OPTIONS: [article,letterpaper,times,12pt,listings-bw,microtype]
#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+TITLE: Resubmission of "Components of Partisan Bias in Multi-Party Systems" to /Political Geography/
#+AUTHOR: double blind review

* Cover letter for RnR
July 4, 2016

Halvard Buhaug, PhD 
Associate Editor
Political Geography

Dear Dr. Buhaug: My co-authors and I have revised our manuscript and are re-submitting it for your consideration and for a second review. 

We addressed all concerns by reviewers, either in the text or in a new on-line appendix. This letter explains how we have done it. 

We accepted all but two points raised by the reviewers---and have corrected or clarified the text and analysis or elaborated based on critiques and recommendations. We quote below the points raised by the reviewers requiring our attention, following each with what we did and where, or did not do and why. 

In addition to reviewers' feedback, we updated all analysis to include 2015 election returns (data that was still unavailable when we prepared the original manuscript) and included secciones that were split in the period of observation due to overpopulation. These secciones had been dropped from the original analysis to save time (recovering them required a good deal of effort). These units are relatively unimportant in sheer numbers (175 overpopulated secciones were split into 5034 new units in the period, out of a total of 66 thousand). But they are concentrated in suburban areas with fast demographic growth since the 1990s. The revised estimates support the the same substantive conclusions, although some individual estimates have changed. 

The new on-line appendix provides detail of our estimation procedure, with a step-by-step explanation of how to prepare data, invoke hypothetical election generation, and specify the Bugs model. At time of publication, we will archive replication code, and data along with this appendix---which will support straightforward replication.

The revised manuscript is 9,768 words long, inclusive (checked with \url{http://app.uio.no/ifi/texcount/online.php}). 
File: redMexBias09.tex
Sum count: 9768
Words in text: 8356
Words in headers: 44
Words outside text (captions, etc.): 1368
Number of headers: 10
Number of floats/tables/figures: 7
Number of math inlines: 89
Number of math displayed: 5

We are confident that the review process has allowed us to improve our manuscript, and hope that the revised version will be acceptable for publication.

Yours sincerely,

Eric Magar, corresponding author

* Reviewer #2
** NO_ACTION_NEEDED This MS deals with partisan bias, in terms of discrepancies between seat and vote shares, looking more closely at three particular sources of such bias. Using data from recent Mexican elections, the paper details a procedure on how to calculate the different sources of this bias in single-member district systems where more than two parties compete.
- Actions taken: none, reviewer asks nothing from us here. 
** NO_ACTION_NEEDED I have to admit from the outset that I'm no expert on this particular topic, although I am familiar with it and work on topics that are not too far removed. Hence, my comments are those of a "generalist reviewer", and are more related to the framing of the paper and different conceptual issues that are not entirely clear to me.
- Actions taken: none, reviewer asks nothing from us here. 
** NO_ACTION_NEEDED But, my overall impression of this MS is that it has the potential to make a nice contribution to the literature and study of partisan bias, not the least because the authors provide a very clear template describing how others could go about in calculating partisan bias in other single-member district system. The summary of sources of partisan biases and the comprehensive treatment and discussion of the issue also makes for a good overview, also for those not working closely on the topic (such as myself). The methods and design are transparent, and mostly well justified, and from what I can understand the analysis is well conducted. I think this could become a publishable article, even in a top outlet such as Political Geography, without too much extra effort on the part of the authors. Still, there are a few things that need to be revisited before the MS is publishable.
- Actions taken: none, reviewer asks nothing from us here. 
** CONCEDED The first issue relates to the "dual framing" of the paper: There is the methodological procedure for calculating sources of bias when there are more than two parties, and there are the substantive results on party biases for the larger Mexican parties. I think the main contribution is the former and this is also mostly how this paper is framed. However, there are parts of the paper that reads as if the results for Mexican bias is the key contribution, and the "dual framing" is also reflected in the rather lengthy (but well written) sections on Mexico starting on p.13.
- Action taken: conceded.
- Explanation: Issue addressed together with next two points.
** CONCEDED I would go for a purer methodological framing of this paper, and make even clearer that Mexico is "just" an application/illustration (even if it is an interesting one, and for a large country). This could potentially go together with shortening the discussion on Mexico, and  freeing up some more space for discussion about the methodological choices and potential problems, conceptual discussions of the various sources of bias etc. There is another particular reason why I think this way of framing the paper is advantageous: As the authors remark, Mexico is a mixed-member electoral system, with a PR tier to reduce disproportionality. This is completely left out of the authors' analysis. While the authors make some pertinent remarks about effects of partisan bias in the single-member tier on political behavior on pp.13-14, it is still the case that we cannot learn much about the overall extent of partisan bias and issues of representation in the Mexican system from this analysis: There will be in all likelihood be a huge upwards bias, and statements such as those made in the abstract concerning the "partisan bias in favor of Mexico's former hegemonic ruling party" etc will be misleading to those who just skim the paper and do not read carefully. If the authors want to make a substantive contribution on partisan bias in a particular country, they would then either need to incorporate the PR tier when discussing overall partisan bias in Mexico, or choose another country  that is a pure single-member system.
- Action taken: conceded, use a methodological framing and downplay the case study.
- Explanation: Issue addressed together with next point. 
** CONCEDED However, if the authors rather chose to frame this even more clearly as a methodological contribution with single-member tier of Mexico as an illustration, I think this issue is not too big (substantive conclusions on overall bias in Mexico would still need to come with some clear caveats, however, so the abstract, for example, would need re-phrasing.
- Action taken: conceded.
- Explanation: Reviewer #2 recommended reframing the manuscript more clearly as a methodological contribution with analysis of the single-member tier of Mexico as an illustration. We have adopted this recommendation, rewriting the introduction and the abstract accordingly. We also trimmed the disussion of Mexico considerably, especially section 4 on Diputado elections, but also section 5 on malapportionment. This is a very clear improvement in the manuscript: the sharp focus in the method to measure partisan bias sources in multi-party competition helps avoid the thorny issue of dropping the PR tier from the analysis. We are grateful to Reviewer #2 for this recommendation. 
** NO_ACTION_NEEDED I basically buy the approach, and the different sources of bias all seem plausible and are well discussed. Still, there are a couple of things that could be discussed/elaborated on:
   CLOSED: [2016-06-10 Fri 16:36]
- Actions taken: none, reviewer asks nothing from us here. 
** CONCEDED First, it is not clear from the outset how measuring pure partisan bias is/can be differentiated from biases related to the size of the party and characteristics of the system favoring larger parties in general (not because of the party's identity, but because of its size). For example, consider two hypothetical elections in which two parties A and B receive the exact same vote share in all districts in a given election. In election 1, A receives 51% and B 49% of votes, in all districts, and A receives all delegates. In election 2, B receives 51% in all districts and all delegates. Now, to me, I wouldn't say that the system is necessarily biased in favor of  A in the first election and B in the second; this is not about the party's identity but about the responsiveness of the system (which does not change from election 1 to 2). An early clarifying discussion, which should be really simple so that non-experts can understand, of how such issues are conceptually handled when delineating what is partisan bias, and a clarification if this truly matters for any of the sources of bias calculated would be very welcome.
- Action taken: conceded. 
- Explanation: As suggested by Reviewer #2, we have expanded the discussion of the rho parameter in section 1 to attempt a clarification of how measuring pure partisan bias is/can be differentiated from biases related to the size of the party and characteristics of the system favoring larger parties in general (not because of the party's identity, but because of its size). 
** CONCEDED Second, given the definition of party bias, I see why the "turnout-based" bias should be part of it. However, one problem here that could be discussed is that turnout in a given district is not something that is exogenously given, but rather affected by the actions and campaign strategies of the different parties. Parties may, for example, campaign harder to get out the vote in districts that are close to call, and some parties may simply be better at winning such districts. Hence, if, let's say the PRI wins a lot of high-turnout districts, it could be due to some inherent actions and capacities of the party, and in a sense it would be wrong to consider this a bias against the PRI in the system. I don't think this is a very big issue, but I think it merits some discussion.
- Action taken: conceded.
- Explanation: Of the three components, the mechanism of malapportionment is easiest to assess because its origin lies squarely in institutions and human choices. Turnout is much harder because mobilization has an endogenous component (cox.munger.1989, rosenstone.hansen.1993). So is border delimination: it could spring from intentional gerrymandering, but could simply be an accident of geography (Johnston's similar-people-live-nearby argument). We have added a paragraph in the results section that deals with this issue (tangentially, at least) in the context of partisan bias volatility in the results. 
** ELABORATED Considering PRI-Green as an alliance and assigning all wins to PRI seems to be a major assumption (which the authors are open about). Now, even if the substantive results for Mexico is downplayed, it would also be interesting from a general point of view to know by how much such assumptions alter the results and conclusions. What happens to the results if PRI-Green is measured as one entity, for example (as suggested on top p.16)?
- Action taken: We have elaborated this recommendation in the on-line appendix.
- Explanation: The revised manuscript retains the manipulation of coalitions described in the original version. But we have added a section in the on-line appendix devoted to elaborating two other approaches to handle partial coalitions: (1) one where the Green's votes are summed to the PRI's across the board (even where the partners did not coalesce), (2) another where the PRI-Green is treated as one entity different from the parent parties. We re-estimated the 2015 election using these approaches, and compared them to reported results. We conclude that results change in predictable ways when coalitions are handled differently. We also underscore that partial coalitions are a Mexico-specific feature that should pose no obstacle to estimation in other multi-party competition cases.
** CONCEDED The rationale for studying partisan bias for each election separately is well explained. However, what if one wants to generalize and test for a systematic bias (or even particular systematic such sources) for/against a party within a system that lasted for a specific period of time? I understand that creeping malapportionment and turnout will change by the election, but if researchers want to make such generalizations, how could they apply/alter your framework to produce (at least rough) tests of this. It's interesting to come up with exact numbers for a particular election, but sometimes the question is whether this is an inherent/more systematic feature of the system, and as the authors show some sources of bias show substantial changes between elections, favoring a party in one and disfavoring it in the next. If the authors could devise a strategy for conducting such a test, this would greatly enhance their contribution, I think.
- Action taken: conceded. 
- Explanation: The paper takes one national election, simulates many more observation points by adding random noise (noise that is plausible given observed district-level data), then estimates partisan bias and components from simulated data. The approach, however, is flexible and can be applied to different research designs. If conclusions over a longer period are of interest (for example, to investigate bias before/after an electoral reform, or to study a given "party system" in contrast to others), an analyst could pool elections in the period and either use the Linzer multiplication approach (one election at a time, then pool simulations), or simply use the pooled data for direct estimation. The revised manuscript makes note of this in the concluding remarks.
** DEFENDED Very minor point: Population levels in districts are based on linear interpolations between censuses. Following standard models of population growth, it would be more appropriate to assume constant population growth rates over the time interval, which can easily be calculated (meaning that population growth in absolute numbers will be smaller for earlier years, if growth is positive).
- Action taken: defend our approach, discuss alternative in on-line appendix.
- Explanation: Estimating inter-censal populations is not trivial. The key problem appears to be the choice of a functional form that both smoothes the rate of population growth while also taking the values actually observed on three census years (2000, 2005, and 2010). An exponential form between pairs of censuses does a good job for years between observations, but not before and after, nor does it treat transitions from one census pair to the next smoothly. A polinomial form would allow work with all three census counts, but also seems problematic for projecting populatios beyond 2010. Since all this requires specialized demography knowledge beyond our abilities, we opted for the simpler linear estimation instead. We describe our linear estimation method, and the challenges of the non-linear approach, in the on-line appendix. 
** NO_ACTION_NEEDED All in all, I learned a lot from reading this paper, and I think it is a very good piece of scholarly work. I recommend that the authors are given the chance to revise and resubmit the paper.
- Actions taken: none, reviewer asks nothing from us here. 

* Reviewer #3
** NO_ACTION_NEEDED This article was a pleasure to read and to evaluate. It is well written, with a theory clearly presented, interesting findings, and a contribution to the estimation of seats and votes in multi-party systems. The article brings together three different traditions in the study of seats and votes, unifying them in a model that allows researchers to discriminate the sources of biases in multi-party races. The article will be of interest to those that conduct basic research on seat-vote models as well as those interested in the mechanical properties of electoral rules in Mexico. Consequently, I recommend publication as is.
- Actions taken: none, reviewer asks nothing from us here. 
** NO_ACTION_NEEDED I do not have recommended changes to the article. The article is honest in stating that it is an original and interesting improvement on existing models but not a radically different modeling strategy. I appreciate that the article does not try to oversell their contribution or findings. 
- Actions taken: none, reviewer asks nothing from us here. 
** CONCEDED That said, the authors could be more aggressive in the introduction to convey to readers how the current article changes prior conventional wisdom in the Mexican election and what contributions will result from estimating their model in other electoral systems. Beyond that, I could only hope that every manuscript I have to review would be such an easy and interesting reading.
- Action taken: conceded. 
- Explanation: The introduction of the revised manuscript stresses how our procedure opens up the comparative study of electoral systems. We mention Canada, India, the UK, France, Australia, Chile, and Ireland as some of the cases for the comparative study of partisan bias. Given that we pursued Reviewer #2's recommendation to downplay the Mexican case study in the framing, we have not stressed how our findings jibe with the conventional wisdom in the introduction---we leave this in the discussion that closes the manuscript.
* Reviewer #4
** NO_ACTION_NEEDED This paper intends to identify the relative and (assumed independent) impact of three different components of partisan bias  in the Mexican electoral system. Application case are lower-chamber federal legislative elections 2003-2012. The paper focuses exclusively on the single member districts  component of the Mexican electoral system.
- Actions taken: none, reviewer asks nothing from us here. 
** CONCEDED The objective of this paper is ambitious. The authors claim to combine most important methodical contributions in this context (Grofman et al. 1997, King 1990, Linzer 2012).  More specifically, it aims at separating the relative impact of malapportionment, boundary delimitations, and differential turnout in an additive multinomial logit model. Sometimes, one has the impression, that a failed redistricting reform is at the center of the paper --- which is confusing.
- Action taken: conceded. 
- Explanation: By de-emphasizing the Mexican case in order to highlight the methodological contribution (as recommended by Reviewer #2), we have also done our best to remove Reviewer #4's impression that the failed redistricting reform is confusingly at the center of the paper. Analysis uses the map that was not implemented in 2015 as part of the hypothetical analysis, offering perspective on the effect of reducing malapportionment (much else constant) on our measure of partisan bias and its components.
** CONCEDED Description and discussion of the Mexican electoral system is negligent. The author writes: "Section 4 describes Mexico's mixed-member electoral system, isolating the plurality tier for analysis" (p. 5). The description of the electoral system can actually be found in footnote 5. But  what does 'isolating' mean? The authors state: "We examine, in isolation, the elections held in the single member plurality-win districts. We do so because all voting and most campaigning take place in the plurality tier." The reviewer considers this legitimation as not sufficient. Note that the current Mexican electoral system includes stipulations balancing excessive partisan bias and including compensation schemes. More specifically, the electoral law prescribes an upper bound of seat-vote deviation of 8%. The is not referred in the paper. Why ? Actually, estimating partisan bias for the SMD component exclusively without referring to this stipulation seems to be misleading.
- Action taken: conceded. 
- Explanation: While analysis of SMD seats without the compensatory PR tier can be defended, it is no longer necessary. By reframing the paper as a methodological contribution with an illustrative (and interesting) application to the plurality tier of the Mexican electoral system---as advised by Reviewer #2---it is justified to ignore the PR tier. We have nonetheless added a paragraph (in section 4) elaborating how the substantive partisan bias results presented for *plurality seats only* have implications for the larger mixed system. We also added the 8 percent over-representation rule in our description of the electoral system, which we had previously neglected to mention.
** CONCEDED One would never seriously propose, to measure partisan bias exclusively for the SMD component in a mixed system like, e.g. the German electoral system.
- Action taken: conceded. 
- Explanation: Answered with point above. 
** DEFENDED It is reasonable to expect strategic coordination of parties, candidates and voters in this context. The paper does not propose a theory what partisan bias means in such a setting. The authors cite Calvo/Micozzi (2005) but do not systematically take into account their arguments, especially the insight that "with more than two parties the relative change in seats depends critically on changes in the number of parties" (Calvo/Micozzi p. 1051)
- Action taken: defended our approach with a concession.
- Explanation: The original manuscript was somewhat vague in this respect, miscommunicating the scope of our analysis. Reviewer #4 rightly points to the theoretical potential of strategic elite and voter coordination and the resulting number of parties for our argument. In working this recommendation, however, we soon encountered difficulties, that we attempt to describe next. We therefore believe that the connection between electoral coordination and partisan bias is quite complex and demands a paper in itself. We do elaborate on some of this in a new footnote in the revised menuscript.
- Explanation (continued): If the vote threshold to win another seat can be anticipated, strategic coordination is the attempt to pool votes (or remove opportunities to spread votes thin) in order to reach that threshold. This process occurs at the district level (Cox 1997), but affects the nation-level phenomena that we observe. Other things constant, the threshold should be lower for bias-favored parties than for other parties, and partisan bias should therefore remove incentives for bias-favored parties to coordinate strategically with others. In such context, bias-unfavored parties have incentives to coordinate, joining forces in an attempt to overcome their disadvantage by accruing the large-party bonus associated with parameter rho. These simple statements suggest one obstacle to a theory of what partisan bias means under strategic coordination: it is unlikely that other things remain constant. In particular, gauging the relation between partisan bias (lambda parameters) and strategic coordination is contingent also on parameter rho. A formal exposition of this interrelation is Cox and Katz's (2002, chapter 3) model of how parties value different redistricting plans, where utility is a function of both lambda and rho. Since our paper is focused in lambdas only, we do not undertake such a theory. 
- Explanation (continued): Regarding multipartism, Calvo and Micozzi show (fig. 1-c) that increasing party competition pulls the votes-seats curve leftward. This is precisely what partisan bias achieves---for a favored party only: a more efficient votes to seats conversion. Bias produces a /rightward/ shift for unfavored parties: a /less/ efficient votes to seats conversion. So whereas the effect of multipartism remains symmetric (absent bias, all parties get a seat bonus by reaching much less than 50 percent), partisan bias remains asymmetric. We have added a footnote at the end of section 1 to elaborate this.
** CONCEDED Section 3 is titled 'Measurement via Monte Carlo simulation'. I guess, the authors mean 'estimation'. The one-page section is not very instructive --- it provides no detailed insights to the applied procedure. The description of the modeling approach is not precise enough. (Some details are provided in footnote 14 in the results section).  More details of the formal setup (including the electoral system) are necessary. The derivation from, and the combination of the existing approaches should be precise and transparent.
- Action taken: conceded.
- Explanation: Section 3 now describes the modeling approach more explicitely. A section in the on-line appendix is devoted to this, elaborating on the full applied procedure in a step-by-step approach, also serving as introduction to the code to replicate the analysis (that will be posted on-line upon publication). In particular, the appendix offers detail about Monte Carlo (Linzer) simulation used to generate a large number of hypothetical national elections for each year, and how three methods combine into our proposed procedure. We also replaced `measurement' with `estimation' in the section name. 
** CONCEDED The authors use a multinomial logit type of model --- I missed a discussion of the crucial assumption of the independence of irrelevant alternatives (IIA) which implies equal substitution patterns which may not be met. 
- Action taken: conceded.
- Explanation: Our multinomial logistic regression type of model satisfies the independence of irrelevant alternatives assumption in the same way that King's model does. Quoting him (King p. 168): "the implied assumption of independence of irrelevant alternatives is satisfied here, since the entire stochastic component is conditional on all parties and votes. The only random choice being made is by the electoral system in assigning seats to parties. Therefore, I use the multinomial probability distribution for the number of seats allocated to the J political parties, a straightforward generalization of the binomial". The only difference is our use of P binomial distributions instead of the multinomial. This is now elaborated in the on-line appendix.
** ELABORATED How do the authors account for districts with varying sets and sizes of candidates in the estimation?
- Action taken: clarified in text and expanded in the on-line appendix. 
- Explanation: Districts with varying sets and sizes of candidates pose an obstacle to the Linzer simulation and, in multi-year research designs, to the MCMC estimation. Linzer's (p. 405) approach overcomes this obstacle by treating subsets of districts with different patterns of party contestation separately in the mixture model. The simulated national elections include all parties that contested one district at least (and were not dropped by the analyst at the start of the process). Our single-year research design avoids the obstacle in MCMC estimation (an analyst can adapt the Bugs model to the number of parties in the simulated elections). Our code (see Table A2), however, is prepared to tackle a multi-year problem: a set of dummy variables, one for each party in the analysis, equal 1 if the party contested the election and 0 otherwise, is computed from the data at the outset and fed to the MCMC process; each numerator's and denominator's additive components (the party's lambda * v^rho) is multiplied by the corresponding dummy, so that parties not contesting drop from the likelihood function. We have expanded this in the appendix, with a mention in text.
** ELABORATED On p. 21, the authors state: "Leaving aside the question of how meaningful the estimated quantities are..."  I admit that this statement is somewhat disturbing. The interpretation and usage of the estimated effects seem to be problematic: it is meanwhile established knowledge that coefficients of multiple nonlinear functions (as in MNL)  cannot be interpreted simply based on statistical significance, and even on the sign of a coefficient. Covariates have to be explicitly fixed for explicit values in order to get conditional probabilities / market shares, marginals and elasticies. Insafar the study should reassess the impact of the estimated coefficients for relevant and typical situations, and for the respective partisan biases in terms of  changes in market shares. E.g., illustrative scenarios in Table 1 could be provided for estimated coefficients.
- Action taken: text explains in section 6 why we still discuss individual lambda coefficients first and then assess impact through swing ratios.
- Explanation: In the revised text, we have dropped the claim that "Leaving aside the question of how meaningful the estimated quantities are..." that seems to have triggered Reviewer #4's concern. Yet the general problem remains, and no easy solution seems to be in our sight. We are aware that, unlike OLS coefficients, the logit link in our model is an obstacle for the assessment of individual lambdas' impact on the DV. One common approach (e.g., Clarify) is comparative statics analysis, letting one regressor of interest fluctuate while all others remain constant at mean, mode, or other illustrative values. This approach is inapplicable to partisan bias in a multi-party setting, due to the compositional nature of vote shares (the regressors): when v_p fluctuates, all other vote shares do not remain constant. "Proportional swing" models remove this complication by assuming that votes are won/lost relative to other parties' sizes. Instead of relying on such restrictive approach, the revised manuscript proceeds like the original submission did: discussing lambda estimates' magnitude and polarity first, then assessing their importance through swing ratios analysis of simulated elections---like Linzer does. We have added a footnote towards the end of section 6 justifying how we proceed.
** CONCEDED Table 3 uses OLS regression for deriving swing ratios: "We derive swing ratios by regressing a party's seat shares in simulated elections on the party's simulated vote shares." Does this regression account for the uncertainity/credibility of simulated shares?
- Action taken: conceded, we explain and clarify that, in fact, it does.
- Explanation: Linzer (p. 408) suggests using OLS regressions as an alternative for deriving swing ratios ("Although equation (4) requires no parametric assumptions about the functional relationship between [party p's vote share and p's expected simulated seat share], the relationship between simulated seat shares ... and simulated vote shares ... around [p's mean vote share] will be roughly oftentimes approximately linear. In that event, the slope of a linear regression of [p's simulated seat shares] on [p's simulated vote shares] will be roughly equivalent to the swing ratio estimate"). Linzer simulations represent the plausibility of various national-level election outcomes given the observed district-level conditions of a given election. The uncertainty of the swing ratio estimate is captured by the variance in simulated outcomes (the spread of the cloud in our Figure 2). The standard errors of our regression coefficients are derived from the very same simulations, thus accounting for uncertainty. The on-line appendix reports an alternative (but related) measure: plots of 95-percent confidence intervals around predicted seat shares.

* ToDo list
** Write cover letter explaining changes. The above list of issues has all the substance needed for this letter (and me may even choose to just send that list mostly as it is!). Letter should mention that we re-did all analysis to include 2015 election returns (previously unavailable), and also adding back secciones that were split in the period due to overpopulation. These had been dropped to save time. These units are relatively unimportant in sheer numbers (175 overpopulated secciones were split into 5034 new units in the period). But they are concentrated in suburban areas with fast demographic growth since the 1990s. Estimates for 2003--2012 have changed, but they tell the same general story.
** Conclusion needs to be adapted to the methodological framing---present version seems to emphasize too much the substantive findings.
** Micah/Mike: Which repository for data, code, appendix? github? ericmagar.com? dataverse? several?
** DONE Re-do rri plots with cleaner seccion-to-dostroct aggregations for paper
   CLOSED: [2016-06-07 Tue 04:45]
** DONE Re-do bias estimate plots with 2015 in for paper
   CLOSED: [2016-06-10 Fri 12:27]
** DROPPED Decide if we call it the 2013 map or the 2015 map.
   CLOSED: [2016-06-14 Tue 19:15]
** Make sure census gap mentioned in the text: I mention it in the appendix without introduction
** Mike: The two comments I received from MPSA were:
*** DONE Need a little more detail on the MCMC algorithm
   CLOSED: [2016-06-10 Fri 16:35]
*** Need more context for non-Mexico scholars
   
* ToDo list if we get publication
** Remove circularities btw red.r and analizaEscenarios.r
** DONE verify that error in king's denominator in red.r is innocuous
   CLOSED: [2016-05-24 Tue 02:21]
** Drop above from spaghetti code (never used for Linzer estimation)

** Turn various code files (red.r, linzerElas.r, analizaEscenarios.r...) into single---if longer---script
* NO_ACTION_NEEDED Editor's letter
  CLOSED: [2016-06-10 Fri 16:36]
Ref.:  Ms. No. PG-2218

Dear Dr. Eric Magar,

Three expert reviewers have now commented on your manuscript. Thank you for waiting. Based on these reviews and my own reading, I invite you to resubmit a revised manuscript. You will see from the review reports appended below that all reviewers see considerable merit in your paper, although they also offer constructive advice on how to make the contribution clearer.

Please let me know within the next couple of weeks whether you will proceed to revise and resubmit this manuscript for Political Geography. The revision should be accompanied with a brief anonymous response letter to the referees. Explain what you did to meet their feedback (or did not do, and why). This response must be anonymous (that is, do not sign the letter).

We need the revision back within the next three months. It will then go back to the same referees for another look. The resubmission must stay below 11,000 words (inclusive) to be acceptable for further processing.

To submit a revision, go to http://ees.elsevier.com/jpgq/ and log in as an Author.  You will find your submission record under the menu item 'Submission Needing Revision'.

Your username is: emagar@itam.mx

If you need to retrieve password details, please go to:
http://ees.elsevier.com/jpgq/automail_query.asp

PLEASE NOTE: The journal would like to enrich online articles by visualising and providing geographical details described in Political Geography articles. For this purpose, corresponding KML (GoogleMaps) files can be uploaded in our online submission system. Submitted KML files will be published with your online article on ScienceDirect. Elsevier will generate maps from the KML files and include them in the online article.

Political Geography features the Interactive Map Viewer, http://www.elsevier.com/googlemaps. Interactive Maps visualize geospatial data provided by the author in a GoogleMap. To include one with your article, please submit a .kml or .kmz file and test it online at http://elsevier-apps.sciverse.com/GoogleMaps/verification before uploading it with your submission.

Please let me know if you have any questions or concerns.

Yours sincerely

Halvard Buhaug, PhD
Associate Editor
Political Geography

* DONE Response to editor accepting to do Rnr
  CLOSED: [2016-04-15 Fri 11:29]
Dear Dr. Buhaug, 
It is with great pleasure that I read the good news about our submission. The reviews are constructive, offering substantive advise, and arrived rather fast! I am sure that they will help us improve the manuscript in the hope that it is acceptable for publication in Political Geography. My co-authors and I will gladly proceed with the revise and resubmit. We will send you a revised manuscript within two months. 
Best,

* NO_ACTION_NEEDED Other mails sent
** DONE Mail on kml maps
   CLOSED: [2016-06-10 Fri 16:46]
Dear Dr. Halvard Buhaug, 
My co-authors and I are working towards the revision of our manuscript. We should have it ready soon. I wish to inquire about digital maps that may be appropriate to illustrate the piece. 
I visited Elsevier's Interactive Map Viewer. Unless I missed something, the example articles feature very simple maps pinpointing the studies' area(s). I have, however, prepared more elaborate kml files showing several features of federal districts --- such as coloring secciones according to recent electoral history, or adding bubbles indicating how many voters are registered --- in selected Mexican states. It should be straightforward to represent key variables in the manuscript (district malapportionment, turnout, and boundaries) in these maps. But Elsevier's verification tool will not show my maps. (One example is http://ericmagar.com/data/maps/distFed/googleEarth/bc.kmz).
Two questions come to mind. How could I gauge how much of the problem is due to my inexperience with map-making or to the system's capacity? Would it be suitable to refer readers in a footnote to the repository where my kml files can be downloaded?
Thank you for your advise.
Best,

** DONE Mail 2 coauthors <2016-06-10 Fri>
   CLOSED: [2016-06-10 Fri 16:47]
Dear co-authors, other than recovering from surgery (fractured shoulder in bike accident---painful indeed! but doing much much better), I have spent the last 6 weeks putting together a response to the Political Geography rNr. I have uploaded three items to our github repository for your consideration: 

(A) the revised manuscript redMexBias09.pdf, 
(B) a draft on an on-line appendix redMexBias09appendix.pdf, and 
(C) all elements to write up a cover letter to the editor and referees RefereeReports2redMexBias08.pdf.  

There are still a few revisions that need to be done to address all the referee's comments, but most is ready --- especially the time-consuming re-analysis. 

I am asking you to please make time to have a good look at the three items so that we can to be ready to resubmit the manuscript. I haven't checked the calendar, but the three-month deadline must be a few weeks away. 

Item C includes all the referee's comments broken into bite-size portions. Below each portion, the action I took in the revised manuscript is mentioned, and also a sketch of paragraph or two with a response, when needed, to the referees. These will be the substance for a cover letter. Please comment/critique/revise what I have done. 

When we have agreement on the revisions/rebutals, the manuscript will need a final proof-read and edits to ensure that the English remains correct.

I will finish polishing the on-line appendix when and if the article is accepted for publication. I will also clean my spaghetti code to make replication *much* easier. 

Finally, if the article is accepted, we will need to decide where we want to store the appendix, data and code for replication. 

Hope all is well, I look forward to reading your reactions.

