Nov. 13

* People
** organizers: Eduardo, Lydia Tiede, Cantú
** Susan Scarrow

* Papers, panel 1
**** Mark Jones comments
** Verónica Caro, Amalina Mena-Mora, Jenn Clark -- substantive women rep Mx Chamber
*** Expects women elected by PR to sponsor women's issues than FPTP? why? Empirical... more PR women?
*** Passage rates? PRI still better? PAN worse?
*** What to expect from 50/50 in 2015?
**** 500 offers good number of women for a study -- sell point
** Catherine Reyes-Housholder Leslie Schwindt-Bayer -- presidentas
*** Have they raised political activity of women? men?
*** Does visibility -> participation? Yes
**** Good to use LAPOP
** Escobar-Lemmon, Michelle Taylor-Robinson -- women in pres cabinets
*** qualification vs effectiveness/treatment typology
*** Resumés believable?
*** #PCRs little difference
**** Time to leave =? effectiveness? Not sure

* Panel 2, courts
**** Amanda Driscoll comments
** Dan Brinks UTAustin, why stronger courts in LA?
*** lo/hi autonomy & narrow/broad scope
*** paper useful for my scjn paper, if it ever lifts off again
**** 1975--2010 comparison fantastic
** Julio Ríos, AAFF boud to democratic rule of law? 
*** Judicial regulation of use of law: 
*** court in Colombia defined "internal armed conflict" (hence law of war applies); Peru denied; Mexico silent
**** Sell book as classic question: can/how do courts constrain coercion?
** Lydia Tiede and Royce Carroll, Dissent in Chile's constitutional tribunal
*** Ultra relevant for my paper on scjn
*** Chile has SC and CT, studies latter only -- 7 judges, mixed appointment method (changed 2006, all appointed likewise)
*** Post-reform 10 judges (ties?), concrete instead of abstract review (no general implications)
*** Does not include Piñera
*** TODO Pr(dissent) higher for unconst. than const. winning opinions --- any relation to tie-break rule?
*** TODO How do legislative overrides and dissent look like?

* Panel 3, electoral strategy and outcomes
**** Jonathan Slapin UH comments
** Cantu Groceries for votes: electoral returns of vote-buying?
*** What is vote buying? 
*** Endogeneity, got handout for vote change or because was voting did get handout?
*** TODO Vote-buying is equal opportunity to 3 parties, but NOT doing it lets you out (vote-selling)
*** TODO Race to the bottom: parties need to buy from scratch every round!
** Magar malapportionment and bias
** Carolina Tchitchian, ballot design in elec compet and leg behavior

* Sat, Panel 4, ideology and representation
**** comments Cantú 
** Olivia Miljanik, UH (Business) -- Brazil Labor and left turn
*** 1990s--2000s
*** 4 big parties, 2 union centrals: CUT=PT, FS=PSDB
*** What are bases for PSDB-FS link? for CUT-FS divide? -- structural
**** Nice that shos that within an industry, there are conflicting unions 
**** (Colliers took labor, Murillo sectors, here that not unitary actor in automotive sector)
** Saiegh, Common-space ideology of LA voters
*** Aldrich-McKelvey estimation of "true" location of parties/governments
*** 2010 Latinobarómetro + PELA in 8 countries + Module 3 CSES (new since last time I saw this)
*** Ideology matters more than esrtwhile recognized, once methological issues taken into account
*** Match between voters/legislators in each country (slight leftward drift of elite in all cases)
** Iñaki Sagarzazu, Chavism and Argentine polarization
*** wordfish by slapin for content analysis -- scaling from words
*Panel 5
**** Leslie comments
** Alemán book:
*** 1 govt coal before/after coup in Chile
*** 2 Coauthorship
*** 3 Leg conflict and reallignment
*** 4 party unity
*** 5 leg power of president OJO
*** 6 one more chapter
*** TODO one-dim legislature post coup: Zucco+Lauderdale's control for pro-anti government?
*** TODO The list label/leaders not mentioned, only party. That should be addressed
*** TODO Whipped/unwhipped?
** Amanda Driscoll, diversity in legislatures (descriptive) has drawbacks
*** Responsiveness in Brazil
*** Feeds on Dan Butler's work: black MCs more responsive to putatively black constituents (even out of district!)
*** Sent emails to 10k personalized candidates (names convey clear class/race prompt) to see if they respond
*** TODO Use candidates college education to measure differences? Verifiable?
*** TODO Were there mistakenly sent emails? What happened to response? What counts as a response?
** Taeko Hiroi + Renno, Leg coalitions and obstructionism in Brazilian Congress
*** Dilma won largest congressional base on record, even for constitutional amendment
*** Yet got remarkably little done! gridlock, delays, defeat
*** Paper has fabulous detail on legislative procedure to accelerate or obstruct --- 50% votes since 2010!

Mail to co-authors:

Dear co-authors: 

1. went well, 

2. I followed Mike's advice and broke the apsa paper into 2 pieces: one on party bias (PRQ might be interested), another of autoamtion-party interaction.

3. we have paper on bias starting to look good. 

2. 
